name: myblog
services: 
  mysql:
    image:mysql: 8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=wrodpress
    volumes:
      - mysql-data:/var/lib/mysql
      - /app/myconf:/etc//mysql/conf.d
    restart: always
    networks:
      - blog

  wrodpress: 
    image: wrodpress
    container_name: wrodpress
    ports:
      -"8080:80"
    enviornment: 
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wrodpress
    volumes:
      - wrodpress/var/www/html
    restart: always
    networks:
      - blog
    depends_on:
      - mysql

volumes:
  mysql-data:
  wrodpress:
networks: 
  blog: